"use client";

import Image from "next/image";
import Link from "next/link";
import { ChevronLeft, Heart, Minus, Plus, ShoppingBag, ShoppingCart, Star, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Footer } from "@/components/StoreSections";
import { Header } from "@/components/Header";
import { Product, products, productsForCategory, relatedProducts } from "@/data/store";

type CartLine = { id: string; quantity: number };
const CART_KEY = "better-space-cart";
const WISHLIST_KEY = "better-space-wishlist";

function readIds(key: string) { if (typeof window === "undefined") return []; try { return JSON.parse(localStorage.getItem(key) || "[]") as string[]; } catch { return []; } }
function readCart() { if (typeof window === "undefined") return []; try { return JSON.parse(localStorage.getItem(CART_KEY) || "[]") as CartLine[]; } catch { return []; } }
function money(value: number) { return `Rp ${new Intl.NumberFormat("id-ID").format(value)}`; }

function useStore() {
  const [cart, setCart] = useState<CartLine[]>([]);
  const [wishlist, setWishlist] = useState<string[]>([]);
  const [hydrated, setHydrated] = useState(false);
  useEffect(() => { queueMicrotask(() => { setCart(readCart()); setWishlist(readIds(WISHLIST_KEY)); setHydrated(true); }); }, []);
  const add = (id: string) => setCart((current) => { const next = current.some((line) => line.id === id) ? current.map((line) => line.id === id ? { ...line, quantity: line.quantity + 1 } : line) : [...current, { id, quantity: 1 }]; localStorage.setItem(CART_KEY, JSON.stringify(next)); return next; });
  const setQuantity = (id: string, quantity: number) => setCart((current) => { const next = quantity < 1 ? current.filter((line) => line.id !== id) : current.map((line) => line.id === id ? { ...line, quantity } : line); localStorage.setItem(CART_KEY, JSON.stringify(next)); return next; });
  const toggleWish = (id: string) => setWishlist((current) => { const next = current.includes(id) ? current.filter((item) => item !== id) : [...current, id]; localStorage.setItem(WISHLIST_KEY, JSON.stringify(next)); return next; });
  return { cart, wishlist, add, setQuantity, toggleWish, hydrated, cartCount: cart.reduce((sum, line) => sum + line.quantity, 0) };
}

function PageFrame({ children, cartCount }: { children: React.ReactNode; cartCount: number }) {
  const [menuOpen, setMenuOpen] = useState(false); const [searchOpen, setSearchOpen] = useState(false);
  return <><Header cartCount={cartCount} menuOpen={menuOpen} setMenuOpen={setMenuOpen} searchOpen={searchOpen} setSearchOpen={setSearchOpen}/>{children}<Footer/></>;
}

function Crumbs({ current }: { current: string }) { return <nav className="breadcrumbs shell" aria-label="Jejak navigasi"><Link href="/">Beranda</Link><span>/</span><Link href="/products">Belanja</Link><span>/</span><b>{current}</b></nav>; }

function ProductCard({ product, wishlisted, onWish, onCart }: { product: Product; wishlisted: boolean; onWish: () => void; onCart: () => void }) {
  return <article className="product-card"><Link className="product-image" href={`/products/${product.id}`}><Image src={product.image} alt={product.name} fill sizes="(max-width:640px) 50vw, (max-width:1024px) 33vw, 20vw"/>{product.badge && <span className="product-badge">{product.badge === "New Arrival" ? "Produk Baru" : product.badge}</span>}</Link><div className="product-info"><p className="product-type">{product.productType}</p><h3><Link href={`/products/${product.id}`}>{product.name}</Link></h3><div className="product-bottom"><b>{product.price}</b><div><button className="wish-inline" onClick={onWish} aria-label={`Simpan ${product.name}`} aria-pressed={wishlisted}><Heart size={16} fill={wishlisted ? "currentColor" : "none"}/></button><button className="cart-add" onClick={onCart} aria-label={`Tambah ${product.name} ke keranjang`}><ShoppingCart size={17}/></button></div></div></div></article>;
}

const roomLabels: Record<string, string> = { "living-room": "Ruang Keluarga", bedroom: "Kamar Tidur", "dining-room": "Ruang Makan", "home-office": "Ruang Kerja", storage: "Penyimpanan", lighting: "Pencahayaan", "home-decor": "Dekorasi Rumah" };

export function CollectionPage({ category }: { category?: string }) {
  const store = useStore(); const [sort, setSort] = useState("featured");
  const collection = useMemo(() => [...productsForCategory(category)].sort((a,b) => sort === "low" ? a.numericPrice - b.numericPrice : sort === "high" ? b.numericPrice-a.numericPrice : 0), [category, sort]);
  const title = category ? (productsForCategory(category)[0]?.category || "Furniture") : "Semua Furniture";
  return <PageFrame cartCount={store.cartCount}><main><Crumbs current={title}/><section className="shell collection-page"><div className="collection-intro"><p className="eyebrow">KOLEKSI BETTER SPACE</p><h1>{title}</h1><p>Furniture untuk ruang yang terasa tenang, fungsional, dan benar-benar milik Anda.</p></div><div className="catalogue-layout"><aside className="catalogue-sidebar"><b>Belanja berdasarkan ruang</b>{["all","living-room","bedroom","dining-room","home-office","storage","lighting","home-decor"].map((slug) => <Link key={slug} className={slug === (category || "all") ? "selected" : ""} href={slug === "all" ? "/products" : `/products?room=${slug}`}>{slug === "all" ? "Semua furniture" : roomLabels[slug]}</Link>)}</aside><div><div className="catalogue-toolbar"><span>{collection.length} produk untuk rumah Anda</span><label>Urutkan <select value={sort} onChange={(event) => setSort(event.target.value)}><option value="featured">Pilihan</option><option value="low">Harga: rendah ke tinggi</option><option value="high">Harga: tinggi ke rendah</option></select></label></div><div className="catalogue-grid">{collection.map((product) => <ProductCard key={product.id} product={product} wishlisted={store.wishlist.includes(product.id)} onWish={() => store.toggleWish(product.id)} onCart={() => store.add(product.id)}/>)}</div></div></div></section></main></PageFrame>;
}

export function ProductPage({ product }: { product: Product }) {
  const store = useStore(); const [quantity, setQuantity] = useState(1); const [selected, setSelected] = useState(product.image);
  const related = relatedProducts(product);
  return <PageFrame cartCount={store.cartCount}><main><Crumbs current={product.name}/><section className="shell product-detail"><div className="product-gallery"><div className="detail-image"><Image src={selected} alt={product.name} fill sizes="(max-width:850px) 100vw, 50vw"/></div><div className="gallery-thumbs">{[product.image, "/images/living.jpg", "/images/promo.jpg"].map((image, index) => <button className={selected === image ? "chosen" : ""} onClick={() => setSelected(image)} key={image} aria-label={`Lihat gambar ${product.name} ${index + 1}`}><Image src={image} alt="" fill sizes="100px"/></button>)}</div></div><div className="detail-copy"><p className="eyebrow">{product.category.toUpperCase()}</p><h1>{product.name}</h1><div className="rating"><span><Star size={15} fill="currentColor"/> 4.8</span><a href="#reviews">34 ulasan</a></div><p className="detail-price">{product.price}</p><p>{product.description}</p><dl><div><dt>Material</dt><dd>{product.material}</dd></div><div><dt>Dimensi</dt><dd>{product.dimensions}</dd></div></dl><div className="quantity-row"><span>Jumlah</span><div><button onClick={() => setQuantity(Math.max(1, quantity - 1))} aria-label="Kurangi jumlah"><Minus size={16}/></button><b>{quantity}</b><button onClick={() => setQuantity(quantity + 1)} aria-label="Tambah jumlah"><Plus size={16}/></button></div></div><div className="purchase-actions"><button className="primary-purchase" onClick={() => Array.from({ length: quantity }).forEach(() => store.add(product.id))}><ShoppingBag size={18}/> Tambah ke Keranjang</button><button className="save-product" onClick={() => store.toggleWish(product.id)} aria-pressed={store.wishlist.includes(product.id)}><Heart size={18} fill={store.wishlist.includes(product.id) ? "currentColor" : "none"}/> Simpan</button></div><p className="delivery-note">Gratis ongkir untuk pesanan di atas Rp 1.000.000. Preview ini tidak memproses pembayaran.</p></div></section><section className="shell detail-tabs"><div><b>Detail</b><b>Material</b><b>Dimensi</b></div><p><strong>Material:</strong> {product.material}<br/>{product.description}</p></section>{related.length > 0 && <section className="shell related-section"><div className="section-heading"><h2>Produk Terkait</h2></div><div className="catalogue-grid">{related.map((item) => <ProductCard key={item.id} product={item} wishlisted={store.wishlist.includes(item.id)} onWish={() => store.toggleWish(item.id)} onCart={() => store.add(item.id)}/>)}</div></section>}</main></PageFrame>;
}

export function CartPage() {
  const store = useStore(); if (!store.hydrated) return <PageFrame cartCount={0}><main><Crumbs current="Keranjang Belanja"/><section className="shell bag-page"><div className="empty-commerce"><ShoppingBag size={34}/><h2>Menyiapkan keranjang Anda</h2><p>Memuat produk yang Anda simpan.</p></div></section></main></PageFrame>; const lines = store.cart.map((line) => ({ ...line, product: products.find((product) => product.id === line.id) })).filter((line): line is CartLine & { product: Product } => Boolean(line.product)); const subtotal = lines.reduce((sum, line) => sum + line.quantity * line.product.numericPrice, 0);
  return <PageFrame cartCount={store.cartCount}><main><Crumbs current="Keranjang Belanja"/><section className="shell bag-page"><div><div className="section-heading"><h1>Keranjang Belanja</h1><Link href="/products"><ChevronLeft size={15}/> Lanjut Belanja</Link></div>{lines.length ? <div className="bag-lines">{lines.map(({ product, quantity }) => <article key={product.id}><Link href={`/products/${product.id}`}><Image src={product.image} alt={product.name} width={112} height={112}/></Link><div><p>{product.category}</p><h2><Link href={`/products/${product.id}`}>{product.name}</Link></h2><b>{product.price}</b></div><div className="bag-quantity"><button onClick={() => store.setQuantity(product.id, quantity - 1)} aria-label={`Kurangi ${product.name}`}><Minus size={15}/></button><b>{quantity}</b><button onClick={() => store.setQuantity(product.id, quantity + 1)} aria-label={`Tambah ${product.name}`}><Plus size={15}/></button></div><button className="remove-line" onClick={() => store.setQuantity(product.id, 0)} aria-label={`Hapus ${product.name}`}><Trash2 size={18}/></button></article>)}</div> : <div className="empty-commerce"><ShoppingBag size={34}/><h2>Keranjang Anda masih kosong</h2><p>Pilih furniture untuk membuat ruang sehari-hari terasa lebih baik.</p><Link className="dark-cta" href="/products">Lihat Produk</Link></div>}</div><aside className="order-summary"><h2>Ringkasan Pesanan</h2><p><span>Subtotal</span><b>{money(subtotal)}</b></p><p><span>Pengiriman</span><b>{subtotal >= 1000000 ? "Gratis" : "Dihitung kemudian"}</b></p><hr/><p className="summary-total"><span>Total</span><b>{money(subtotal)}</b></p><button className="primary-purchase" disabled={!lines.length}>Lanjut ke Pengiriman</button><small>Preview ini tidak memproses pembayaran.</small></aside></section></main></PageFrame>;
}

export function WishlistPage() { const store = useStore(); if (!store.hydrated) return <PageFrame cartCount={0}><main><Crumbs current="Produk Favorit"/><section className="shell saved-page"><div className="empty-commerce"><Heart size={34}/><h2>Menyiapkan daftar favorit</h2><p>Memuat produk yang Anda simpan.</p></div></section></main></PageFrame>; const saved = products.filter((product) => store.wishlist.includes(product.id)); return <PageFrame cartCount={store.cartCount}><main><Crumbs current="Produk Favorit"/><section className="shell saved-page"><div className="section-heading"><div><p className="eyebrow">DAFTAR FAVORIT ANDA</p><h1>Produk Favorit</h1></div><Link href="/products">Lihat Produk Lainnya</Link></div>{saved.length ? <div className="catalogue-grid">{saved.map((product) => <ProductCard key={product.id} product={product} wishlisted onWish={() => store.toggleWish(product.id)} onCart={() => store.add(product.id)}/>)}</div> : <div className="empty-commerce"><Heart size={34}/><h2>Simpan produk yang Anda sukai</h2><p>Daftar favorit ini tersimpan pada perangkat Anda ketika membandingkan ruang dan material.</p><Link className="dark-cta" href="/products">Jelajahi Koleksi</Link></div>}</section></main></PageFrame>; }
