"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BedDouble, Box, Headphones, Heart, LampDesk, LayoutGrid, LockKeyhole, PackageCheck, ShoppingCart, Sofa, Table2, Truck, Wrench } from "lucide-react";
import { categories, products, roomCategories } from "@/data/store";

const categoryIcons = { sofa: Sofa, bed: BedDouble, table: Table2, desk: LampDesk, cabinet: Box, lamp: LampDesk, vase: LayoutGrid, tag: PackageCheck };

/** Homepage "Products You May Like" caps at 5 rows x 5 columns on desktop. The rest of the catalogue stays reachable through "View All" (/products). */
const HOME_GRID_LIMIT = 25;
const homeGridProducts = products.slice(0, HOME_GRID_LIMIT);

export function Hero() { return <section id="home" className="hero"><Image src="/images/hero.jpg" alt="Bright contemporary living room with a linen sectional sofa and warm wood furniture" fill priority sizes="100vw" className="hero-image"/><div className="hero-wash"/><div className="shell hero-content"><p className="eyebrow">NEW COLLECTION</p><h1>Beautiful Spaces<br/>For a Better Life</h1><p>Modern furniture for home and office, designed for comfort, function, and lasting style.</p><a href="#products" className="dark-cta">Shop the collection <ArrowRight size={15}/></a></div></section>; }

export function CategoryNavigation() { return <section className="room-nav" aria-label="Shop by room"><div className="shell room-scroll">{roomCategories.map(({label, icon, slug}) => { const Icon = categoryIcons[icon as keyof typeof categoryIcons]; return <Link key={label} href={`/products?room=${slug}`} className="room-link"><span><Icon size={22}/></span>{label}</Link>; })}</div></section>; }

export function CategoryGrid() { return <section id="rooms" className="shell section categories-section"><div className="section-heading"><h2>Featured Categories</h2><Link href="/products">See all categories <ArrowRight size={14}/></Link></div><div className="category-grid">{categories.map((category) => <Link href={`/products?room=${category.slug}`} className="category-card" key={category.name}><Image src={category.image} alt={`${category.name} furniture collection`} fill sizes="(max-width: 640px) 50vw, 33vw"/><span className="card-scrim"/><div><h3>{category.name}</h3><p>{category.description}</p></div><i><ArrowRight size={16}/></i></Link>)}</div></section>; }

export function ProductGrid({ liked, toggleLiked, addToCart }: { liked: string[]; toggleLiked: (id: string) => void; addToCart: (id: string) => void }) { return <section id="products" className="shell section products-section"><div className="products-heading"><h2>Products You May Like</h2><div className="product-tabs" aria-label="Product filters"><button className="active">Best Seller</button><button>New Arrivals</button><button>Special Offer</button><Link href="/products">View All <ArrowRight size={14}/></Link></div></div><div className="product-grid">{homeGridProducts.map((product) => <article className="product-card" key={product.id}><Link className="product-image" href={`/products/${product.id}`}><Image src={product.image} alt={product.name} fill sizes="(max-width: 640px) 50vw, (max-width: 1024px) 33vw, 20vw"/></Link><button className="wish" aria-label={`Add ${product.name} to wishlist`} aria-pressed={liked.includes(product.id)} onClick={() => toggleLiked(product.id)}><Heart size={18} fill={liked.includes(product.id) ? "currentColor" : "none"}/></button><div className="product-info"><p className="product-type">{product.category}</p><h3><Link href={`/products/${product.id}`}>{product.name}</Link></h3><small>Made for everyday living</small><div className="product-bottom"><b>{product.price}</b><button className="cart-add" aria-label={`Add ${product.name} to cart`} onClick={() => addToCart(product.id)}><ShoppingIcon/></button></div></div></article>)}</div></section>; }
function ShoppingIcon() { return <ShoppingCart size={17} strokeWidth={2.1}/>; }

export function CollectionBanner() { return <section id="inspiration" className="shell collection-banner"><Image src="/images/promo.jpg" alt="Warm dining room with timber dining table and natural light" fill sizes="(max-width: 1240px) 100vw, 1200px"/><div className="banner-wash"/><div className="collection-copy"><p className="eyebrow">DINING, MADE TO GATHER</p><h2>Complete Your<br/>Dining Space</h2><p>Timeless dining furniture for meaningful gatherings with family and friends.</p><Link href="/products?room=dining-room" className="dark-cta">Browse dining pieces <ArrowRight size={15}/></Link></div></section>; }

const serviceItems = [[Truck,"Free Shipping","For orders over Rp 1.000.000"],[LockKeyhole,"Secure Payment","Protected payment options"],[Headphones,"Customer Support","Ready to help every day"],[Wrench,"Easy Returns","Simple return process"]] as const;
export function ServiceFeatures() { return <section className="shell service-strip">{serviceItems.map(([Icon,title,body]) => <div key={title}><Icon size={29}/><p><b>{title}</b><span>{body}</span></p></div>)}</section>; }

export function Footer() { return <footer id="contact" className="footer"><div className="shell footer-grid"><div className="footer-brand" id="about"><a href="#home" className="brand"><strong>Better Space</strong><span>FURNITURE FOR A BETTER LIVING.</span></a><p>Furniture pilihan untuk rumah dan ruang kerja yang lebih nyaman, fungsional, dan indah.</p><div className="socials"><a href="#contact" aria-label="Better Space di Instagram">ig</a><a href="#contact" aria-label="Better Space di Facebook">f</a><a href="#contact" aria-label="Better Space di TikTok">tk</a></div></div><div><h3>Belanja</h3>{["Semua Produk","Ruang Keluarga","Kamar Tidur","Ruang Makan","Ruang Kerja","Penyimpanan"].map(x=><a href="#products" key={x}>{x}</a>)}</div><div><h3>Layanan Pelanggan</h3>{["Pusat Bantuan","Lacak Pesanan","Informasi Pengiriman","Pengembalian & Penukaran","Perawatan Produk","Kebijakan Privasi"].map(x=><a href="#contact" key={x}>{x}</a>)}</div><div className="newsletter"><h3>Dapatkan Info Terbaru</h3><p>Produk terbaru, penawaran pilihan, dan ide untuk rumah yang Anda sukai.</p><form onSubmit={(event) => { event.preventDefault(); const status = event.currentTarget.querySelector("output"); if (status) status.textContent = "Terima kasih. Anda sudah terdaftar."; }}><label htmlFor="newsletter-email" className="sr-only">Alamat email</label><input id="newsletter-email" type="email" required placeholder="Alamat email Anda"/><button aria-label="Berlangganan"><ArrowRight size={17}/></button><output aria-live="polite"/></form></div></div><div className="shell footer-bottom"><span>© 2026 Better Space. Hak cipta dilindungi.</span><span>Pembayaran diterima: BCA · Mandiri · Visa · Mastercard · GoPay</span></div></footer>; }
