"use client";

import Image from "next/image";
import { ArrowRight, BedDouble, Box, Headphones, Heart, LampDesk, LayoutGrid, LockKeyhole, PackageCheck, ShoppingCart, Sofa, Table2, Truck, Wrench } from "lucide-react";
import { categories, products, roomCategories } from "@/data/store";

const categoryIcons = { sofa: Sofa, bed: BedDouble, table: Table2, desk: LampDesk, cabinet: Box, lamp: LampDesk, vase: LayoutGrid, tag: PackageCheck };

export function Hero() { return <section id="home" className="hero"><Image src="/images/hero.jpg" alt="Bright contemporary living room with a linen sectional sofa and warm wood furniture" fill priority sizes="100vw" className="hero-image"/><div className="hero-wash"/><div className="shell hero-content"><p className="eyebrow">NEW COLLECTION</p><h1>Beautiful Spaces<br/>For a Better Life</h1><p>Modern furniture for home and office, designed for comfort, function, and lasting style.</p><a href="#products" className="dark-cta">Shop the collection <ArrowRight size={15}/></a></div></section>; }

export function CategoryNavigation() { return <section className="room-nav" aria-label="Shop by room"><div className="shell room-scroll">{roomCategories.map(({label, icon}) => { const Icon = categoryIcons[icon as keyof typeof categoryIcons]; return <a key={label} href="#rooms" className="room-link"><span><Icon size={22}/></span>{label}</a>; })}</div></section>; }

export function CategoryGrid() { return <section id="rooms" className="shell section categories-section"><div className="section-heading"><h2>Featured Categories</h2><a href="#products">See all categories <ArrowRight size={14}/></a></div><div className="category-grid">{categories.map((category) => <a href="#products" className="category-card" key={category.name}><Image src={category.image} alt={`${category.name} furniture collection`} fill sizes="(max-width: 640px) 50vw, 33vw"/><span className="card-scrim"/><div><h3>{category.name}</h3><p>{category.description}</p></div><i><ArrowRight size={16}/></i></a>)}</div></section>; }

export function ProductGrid({ liked, toggleLiked, addToCart }: { liked: string[]; toggleLiked: (id: string) => void; addToCart: () => void }) { return <section id="products" className="shell section products-section"><div className="products-heading"><h2>Products You May Like</h2><div className="product-tabs" aria-label="Product filters"><button className="active">Best Seller</button><button>New Arrivals</button><button>Special Offer</button><a href="#products">View All <ArrowRight size={14}/></a></div></div><div className="product-grid">{products.map((product) => <article className="product-card" key={product.id}><div className="product-image"><Image src={product.image} alt={product.name} fill sizes="(max-width: 640px) 50vw, (max-width: 1024px) 33vw, 20vw"/><button className="wish" aria-label={`Add ${product.name} to wishlist`} aria-pressed={liked.includes(product.id)} onClick={() => toggleLiked(product.id)}><Heart size={18} fill={liked.includes(product.id) ? "currentColor" : "none"}/></button></div><div className="product-info"><p className="product-type">{product.category}</p><h3>{product.name}</h3><small>Made for everyday living</small><div className="product-bottom"><b>{product.price}</b><button className="cart-add" aria-label={`Add ${product.name} to cart`} onClick={addToCart}><ShoppingIcon/></button></div></div></article>)}</div></section>; }
function ShoppingIcon() { return <ShoppingCart size={17} strokeWidth={2.1}/>; }

export function CollectionBanner() { return <section id="inspiration" className="shell collection-banner"><Image src="/images/promo.jpg" alt="Warm dining room with timber dining table and natural light" fill sizes="(max-width: 1240px) 100vw, 1200px"/><div className="banner-wash"/><div className="collection-copy"><p className="eyebrow">DINING, MADE TO GATHER</p><h2>Complete Your<br/>Dining Space</h2><p>Timeless dining furniture for meaningful gatherings with family and friends.</p><a href="#products" className="dark-cta">Browse dining pieces <ArrowRight size={15}/></a></div></section>; }

const serviceItems = [[Truck,"Free Shipping","For orders over Rp 1.000.000"],[LockKeyhole,"Secure Payment","Protected payment options"],[Headphones,"Customer Support","Ready to help every day"],[Wrench,"Easy Returns","Simple return process"]] as const;
export function ServiceFeatures() { return <section className="shell service-strip">{serviceItems.map(([Icon,title,body]) => <div key={title}><Icon size={29}/><p><b>{title}</b><span>{body}</span></p></div>)}</section>; }

export function Footer() { return <footer id="contact" className="footer"><div className="shell footer-grid"><div className="footer-brand" id="about"><a href="#home" className="brand"><strong>RUMAIO</strong><span>HOME FOR BETTER LIVING</span></a><p>Furniture thoughtfully chosen to make your home and workspace more comfortable, functional, and beautiful.</p><div className="socials"><a href="#contact" aria-label="Rumaio on Instagram">ig</a><a href="#contact" aria-label="Rumaio on Facebook">f</a><a href="#contact" aria-label="Rumaio on TikTok">tk</a></div></div><div><h3>Shop</h3>{["All Products","Living Room","Bedroom","Dining Room","Home Office","Storage"].map(x=><a href="#products" key={x}>{x}</a>)}</div><div><h3>Customer Care</h3>{["Help Center","Track Order","Shipping Information","Return & Exchange","Product Care","Privacy Policy"].map(x=><a href="#contact" key={x}>{x}</a>)}</div><div className="newsletter"><h3>Get Our Latest Updates</h3><p>New arrivals, special offers, and ideas for a home you love.</p><form onSubmit={(event) => { event.preventDefault(); const status = event.currentTarget.querySelector("output"); if (status) status.textContent = "Thank you. You are on the list."; }}><label htmlFor="newsletter-email" className="sr-only">Email address</label><input id="newsletter-email" type="email" required placeholder="Your email address"/><button aria-label="Subscribe"><ArrowRight size={17}/></button><output aria-live="polite"/></form></div></div><div className="shell footer-bottom"><span>© 2026 Rumaio. All rights reserved.</span><span>Payments accepted: BCA · Mandiri · Visa · Mastercard · GoPay</span></div></footer>; }
